MasterInstanceType: t2.micro
SlaveInstanceType: t2.micro
PublicSlaveInstanceType: t2.micro
NATInstanceType: t2.micro

PublicSlaveInstanceCount: 1
SlaveInstanceCountDesired: 1
SlaveInstanceCount: 2
MasterEbsOptimized: false
SlaveEbsOptimized: false
